// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA88y5V4k1Z--Sk_0Az4qqRfzLlgJ-KPHM',
    appId: '1:986020307657:android:fc7becea04cd6472596318',
    messagingSenderId: '986020307657',
    projectId: 'antiradar-5a2b5',
    storageBucket: 'antiradar-5a2b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXiuSK9R2JZpLh9FG2HzCMl0xXGMNsOgE',
    appId: '1:986020307657:ios:01765554f8ea78c4596318',
    messagingSenderId: '986020307657',
    projectId: 'antiradar-5a2b5',
    storageBucket: 'antiradar-5a2b5.appspot.com',
    iosBundleId: 'com.example.antiradar',
  );
}
